---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-super-linter:
    uses: https://github.com/shaneholloman/kordia-super-linter/blob/main/.github/workflows/super-linter.yaml@main
