---
name: Trivy Scan Deps for CVEs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Run Trivy vulnerability scanner in repo mode
        # https://github.com/marketplace/actions/aqua-security-trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
